function Trial = loadTorque(filename, dataLines)
% IMPORTFILE  Imports data from a text file.
%   Trial = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%   the default selection.  Returns the data as a table.
%
%   Trial = IMPORTFILE(FILE, DATALINES) reads data for the specified
%   row interval(s) of text file FILENAME. Specify DATALINES as a
%   positive scalar integer or a N-by-2 array of positive scalar integers
%   for dis-contiguous row intervals.
%
%   Example:
%   Trial = importfile("C:\Users\calvi\Downloads\Data Analysis - Balance Robot Validation-20220318T185159Z-001\MLBAL02\MLBAL02\Trial.forces", [6, Inf]);
%
%   See also READTABLE.
%
%   Auto-generated by MATLAB on 01-May-2023 09:47:45

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [6, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 29);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Sample", "FX1", "FY1", "FZ1", "X1", "Y1", "Z1", "MZ1", "FX2", "FY2", "FZ2", "X2", "Y2", "Z2", "MZ2", "FX3", "FY3", "FZ3", "X3", "Y3", "Z3", "MZ3", "FX4", "FY4", "FZ4", "X4", "Y4", "Z4", "MZ4"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["FX3", "FY3", "FZ3", "X3", "Y3", "Z3", "MZ3", "FX4", "FY4", "FZ4", "X4", "Y4", "Z4", "MZ4"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["FX3", "FY3", "FZ3", "X3", "Y3", "Z3", "MZ3", "FX4", "FY4", "FZ4", "X4", "Y4", "Z4", "MZ4"], "ThousandsSeparator", ",");

% Import the data
Trial = readtable(filename, opts);

end