function Trial = importfile(filename)
% IMPORTFILE  Imports data from a text file
%   Trial = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%   the default selection.  Returns the data as a table.
%
%   Trial = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%   interval(s) of text file FILENAME. Specify DATALINES as a positive
%   scalar integer or a N-by-2 array of positive scalar integers for
%   dis-contiguous row intervals.
%
%   Example:
%   Trial = importfile("C:\Users\panti\OneDrive - UBC\ML balance\data\MLBAL01\Trial5.csv");
%
%   See also READTABLE.
%
%  Auto-generated by MATLAB on 10-Jul-2023 01:55:57

    %% Set up the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 122);
    
    % Specify range and delimiter
    opts.DataLines = [2, Inf];
    opts.Delimiter = ",";
    
    % Specify column names and types
    opts.VariableNames = ["Frame", "Time", "RInfTrag", "VarName4", "VarName5", "RInfOrb", "VarName7", "VarName8", "LInfTrag", "VarName10", "VarName11", "LInfOrb", "VarName13", "VarName14", "RAC", "VarName16", "VarName17", "LAC", "VarName19", "VarName20", "Manub", "VarName22", "VarName23", "C7", "VarName25", "VarName26", "T5", "VarName28", "VarName29", "RPSIS", "VarName31", "VarName32", "VSacral", "VarName34", "VarName35", "LPSIS", "VarName37", "VarName38", "RASIS", "VarName40", "VarName41", "LASIS", "VarName43", "VarName44", "RTAT", "VarName46", "VarName47", "RTPT", "VarName49", "VarName50", "RBAT", "VarName52", "VarName53", "RBPT", "VarName55", "VarName56", "RKnee", "VarName58", "VarName59", "RTAS", "VarName61", "VarName62", "RTPS", "VarName64", "VarName65", "RBAS", "VarName67", "VarName68", "RBPS", "VarName70", "VarName71", "RAnkle", "VarName73", "VarName74", "RHeel", "VarName76", "VarName77", "RVMH", "VarName79", "VarName80", "RToe", "VarName82", "VarName83", "LTAT", "VarName85", "VarName86", "LTPT", "VarName88", "VarName89", "LBAT", "VarName91", "VarName92", "LBPT", "VarName94", "VarName95", "LKnee", "VarName97", "VarName98", "LTAS", "VarName100", "VarName101", "LTPS", "VarName103", "VarName104", "LBAS", "VarName106", "VarName107", "LBPS", "VarName109", "VarName110", "LAnkle", "VarName112", "VarName113", "LHeel", "VarName115", "VarName116", "LVMH", "VarName118", "VarName119", "LToe", "VarName121", "VarName122"];
    opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
    
    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";
    
    % Import the data
    Trial = readtable(filename, opts);
end
